import { Inter } from "next/font/google";
import "./globals.css";
import Header from "@/components/header";
import StartPage from "@/components/startpage";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Lama Dev Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className={inter.className}>
      <head>
        <meta name="description" content={metadata.description} />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <div className="font-rachel ">
          <Header />
          <StartPage />
          <div>
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}


